workflows:
  android-apk:
    name: Android APK
    max_build_duration: 60
    environment:
      flutter: 3.44.0
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
